
export default {
  // TOPIC
  TOPIC_ADD: 'TOPIC_ADD',
  TOPIC_UPDATE: 'TOPIC_UPDATE',
  TOPIC_DELETE: 'TOPIC_DELETE',
  
  // TASK
  TASK_ADD: 'TASK_ADD',
  TASK_UPDATE: 'TASK_UPDATE',
  TASK_DELETE: 'TASK_DELETE',

}